name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 keyboard monitorcontrol Pillow screeninfo pyinstaller

    - name: Install Windows-specific dependencies
      if: runner.os == 'Windows'
      run: pip install pywin32

    - name: Build Windows executable
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --icon=myicon.ico --add-data "myicon.ico;." --noupx -n MonitorNap-Windows --distpath dist/windows --workpath build/windows monitornap.py

    - name: Build non-Windows executable
      if: runner.os != 'Windows'
      run: |
        pyinstaller --onefile --windowed --add-data "myicon.ico:." --noupx -n MonitorNap-${{ runner.os }} --distpath dist/${{ runner.os }} --workpath build/${{ runner.os }} monitornap.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: monitornap-${{ runner.os }}
        path: |
          dist/${{ runner.os }}/*
          dist/windows/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
        files: artifacts/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
